name: Build Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [win32, darwin, linux]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.18.1'

    - name: Install dependencies
      run: npm install

    - name: Build for ${{ matrix.platform }}
      run: npm run dist -- --linux --win --mac
      if: matrix.platform == 'all'
      env:
        CI: true

    - name: Build for ${{ matrix.platform }}
      run: npm run dist -- --${{ matrix.platform }}
      env:
        CI: true

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: electron-app-${{ matrix.platform }}
        path: dist

