name: Build Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.18.1'
        npm-version: '10.9.2'

    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install build tools (Linux only)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Install dependencies
      run: npm install --no-cache --verbose --force --no-audit 

    - name: Get current version from package.json
      id: get_version
      run: echo "CURRENT_VERSION=$(node -p \"require('./package.json').version\")" >> $GITHUB_ENV

    - name: Check for previous version
      id: check_version
      run: |
        if [ -f last_version.txt ]; then
          LAST_VERSION=$(cat last_version.txt)
          echo "Last version: $LAST_VERSION"
          echo "Current version: $CURRENT_VERSION"
          if [ "$CURRENT_VERSION" == "$LAST_VERSION" ]; then
            echo "No new version detected. Exiting."
            exit 0
          fi
        else
          echo "No previous version found. Proceeding with build."
        fi

    - name: Clean dist directory
      run: rm -rf dist/*  # Remove all content in the dist directory
      shell: bash

    - name: Ensure build directory exists
      run: mkdir -p dist
        
    - name: Build for specific platform
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          npm run dist -- --linux
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          npm run dist -- --mac
        elif [ "${{ matrix.os }}" == "windows-latest" ]; then
          npm run dist -- --win
        else
          echo "Unsupported platform: ${{ matrix.os }}"
          exit 1
        fi
      env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Pass the token as an environment variable
      shell: bash  # Use bash for Linux and macOS

    - name: Check if build directory exists
      run: |
        if [ ! -d "dist" ]; then
          echo "Error: dist directory not found."
          exit 1
        fi
      shell: bash  # Use bash for Linux and macOS
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: electron-app-${{ env.VERSION }}-${{ matrix.os }}
        path: |
          dist/*.deb
          dist/*.exe
          dist/*.AppImage
          dist/*.dmg
        if-no-files-found: error
        
    - name: Save current version
      run: echo "${{ env.CURRENT_VERSION }}" > last_version.txt
      
